volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    env_file: .env
    restart: always
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    restart: always
    volumes:
      - frontend_static:/app/build/

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    restart: always
    volumes:
      - backend_static:/backend_static/
      - frontend_static:/frontend_static/
      - media:/media/
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend