server { 
    listen 80; 
    server_tokens off;

    location /api/ { 
        proxy_pass http://backend:8000; 
        proxy_set_header Host $host; 
    } 

    location /admin/ { 
        proxy_pass http://backend:8000; 
        proxy_set_header Host $host; 
    } 

    location /media/ {
        alias /media/;
        # optional: try_files $uri $uri/ =404;
    } 

    location /static/admin/ {
        alias /static/admin/;
    }

    location /static/rest_framework/ {
        alias /static/rest_framework/;
    }

    location / { 
        root /static/; 
        index index.html; 
        try_files $uri $uri/ /index.html; 
    } 
}