server { 
    listen 80; 
    server_tokens off;

    location /api/ { 
        proxy_pass http://backend:8000; 
        proxy_set_header Host $host; 
    } 

    location /admin/ { 
        proxy_pass http://backend:8000; 
        proxy_set_header Host $host; 
    } 

    location /media/ {
        alias /app/media/;  # Serve media files from Docker volume
        # optional: try_files $uri $uri/ =404;
    } 

    location /static/admin/ {
        alias /app/static/admin/;  # Serve admin static files from Docker volume
    }

    location /static/rest_framework/ {
        alias /app/static/rest_framework/;  # Serve DRF static files from Docker volume
    }

    location / { 
        root /static/; 
        index index.html; 
        try_files $uri $uri/ /index.html; 
    } 
}